from quantumcircuit import QuantumCircuit
from multiprocessing import Pool
import time


class GKSimulator:
    """
    Class qui reçoit un QuantumCircuit et dispose d'une méthode pour mesurer une observable de Pauli donnée.
    """
    def __init__(self):
        pass

    def run(self,q: QuantumCircuit):
        # circ_id=range(q.circuits)
        nb_circuits=len(q.circuits)
        circuits=range(nb_circuits)
        args = [(q,circuit) for circuit in circuits]
        if nb_circuits>1:
            with Pool(processes=8) as pool:
                results= pool.starmap(self.run_single, args)
        else:
            results=[]
            for arg in args:
                results.append(self.run_single(*arg))
        return results



    def run_single(self,q,circ_idx):
        # r=[]
        probabilities={}
        nb_no_commute=0     # Check if observables commutes with all generators for measurement
        for stab in q.generators[circ_idx]:
            parity_check=0
            for idx in range(q.n_qubits[circ_idx]):
                obs=q.observables[circ_idx][str(idx)]
                stab_op=stab[str(idx)]
                if stab_op!='i' and stab_op!=obs and obs!='i':
                    parity_check+=1
            if parity_check%2!=0:
                nb_no_commute+=1
        for eigen_value in q.eigen_values[circ_idx]: # Dictionnary initialisation for which eigenvalue(s) we want probabilities
            probabilities[eigen_value]=0.0
        if nb_no_commute!=0:    # If observable does not commute with all generators: P(+1)=P(-1)=0.5
            if '+' in probabilities:
                probabilities['+']=0.5
            if '-' in probabilities:
                probabilities['-']=0.5
        else:   # If observable commutes with all generators, check whether observable or -observable is in the group generated by the generators
            stabilizers_group = self.generate_stabilizers(q.generators[circ_idx],q.n_qubits[circ_idx])      # Generate group
            strstabs=[]
            for stabil in stabilizers_group:
                strstab=''
                for idex in range(q.n_qubits[circ_idx]):
                    strstab+=stabil[str(idex)]
                strstabs.append(stabil['phase']+strstab)
            if q.observables[circ_idx]['as_string'] in strstabs:    # If observable in group: P(+1)=1, P(-1)=0
                if '+' in probabilities:
                    probabilities['+']=1.0
                if '-' in probabilities:
                    probabilities['-']=0.0
            else:   # If -observable in group: P(+1)=0, P(-1)=1
                if '+' in probabilities:
                    probabilities['+']=0.0
                if '-' in probabilities:
                    probabilities['-']=1.0



        # r.append(probabilities)
        return probabilities#r
    
    def generate_stabilizers(self,generators, num_qubits,num_exec = 10):############### Fait avec ChatGPT
        """
        Generate all possible stabilizers from a list of generators with optional phases.

        Parameters:
            generators (list of dict): List of generators, where each generator is a
                                    dictionary mapping qubit indices to Pauli operators
                                    (e.g., {'0': 'z', '1': 'x', 'phase': '+'}).
            num_qubits (int): The total number of qubits in the system.

        Returns:
            list of dict: All possible stabilizers generated by the input.
        """
        def pauli_multiply(pauli1, pauli2):########## Fait avec ChatGPT
            """Multiply two Pauli operators represented as dictionaries, including phase."""
            result = {}
            phase = 1  # Track the overall phase (+1 or -1)

            # Combine operators at each qubit
            for q in range(num_qubits):
                q = str(q)
                op1 = pauli1.get(q, 'i')  # Default to identity if not present
                op2 = pauli2.get(q, 'i')  # Default to identity if not present
                
                if op1 == op2:
                    result[q] = 'i' if op1 != 'i' else 'i'  # Same operators cancel to identity
                elif 'i' in (op1, op2):
                    result[q] = op1 if op2 == 'i' else op2  # Identity has no effect
                else:
                    # Compute the resulting operator and phase
                    pair = {op1, op2}
                    if pair == {'x', 'y'}:
                        result[q] = 'z'
                        phase *= 1 if op1 == 'x' else -1
                    elif pair == {'y', 'z'}:
                        result[q] = 'x'
                        phase *= 1 if op1 == 'y' else -1
                    elif pair == {'z', 'x'}:
                        result[q] = 'y'
                        phase *= 1 if op1 == 'z' else -1

            # Combine phases
            phase1 = pauli1.get('phase', '+')  # Default phase is +
            phase2 = pauli2.get('phase', '+')
            phase_combination = {
                ('+', '+'): '+', ('+', '-'): '-',
                ('-', '+'): '-', ('-', '-'): '+',
            }
            result['phase'] = phase_combination[(phase1, phase2)]

            # Apply the phase due to anticommutation
            if phase == -1:
                result['phase'] = '-' if result['phase'] == '+' else '+'

            return result

        # Start with the identity element
        identity = {str(q): 'i' for q in range(num_qubits)}
        identity['phase'] = '+'
        stabilizers = {frozenset(identity.items())}  # Use set for duplicate removal


        for gen in generators:
            stabilizers.add(frozenset(gen.items()))

        # Iteratively build the stabilizer group
        execution=0
        current_layer = {frozenset(gen.items()) for gen in generators}
        while current_layer and execution<num_exec:
            next_layer = set()
            for stab in current_layer:
                stab_dict = dict(stab)
                for gen in generators:
                    result = pauli_multiply(stab_dict, gen)
                    result_frozen = frozenset(result.items())
                    if result_frozen not in stabilizers:
                        stabilizers.add(result_frozen)
                        next_layer.add(result_frozen)
                    execution+=1
            current_layer = next_layer
        # Convert stabilizers back to list of dictionaries
        return [dict(stab) for stab in stabilizers]

