"""
Miscellaneous utility functions for generating and saving quantum circuits.
"""

import json

import numpy as np

from quantumcircuit import QuantumCircuit


def generate_random_circuits(
    num_circuits,
    num_qubits,
    num_blocks,
    num_gates,
    one_qubit_gates_pool=["h", "x", "y", "z", "s"],
    two_qubit_gates_pool=["cx"],
    observables_pool=["i", "x", "y", "z"],
    eigenvalues_pool=["+", "-"],
    seed=None,
):
    """
    Generate random quantum circuits. The quantum circuits are generated by randomly selecting the number of qubits, observables, eigenvalues, one-qubit gates, and two-qubit gates. The number of blocks and gates per block are also randomly selected.

    Parameters:
    -----------
    num_circuits : int
        Number of quantum circuits to generate.
    num_qubits : int
        Number of qubits in the quantum circuit.
    num_blocks : int
        Number of blocks in the quantum circuit.
    num_gates : int
        Number of gates per block in the quantum circuit.
    one_qubit_gates_pool : list
        List of one-qubit gates to choose from.
    two_qubit_gates_pool : list
        List of two-qubit gates to choose from.
    observables_pool : list
        List of observables to choose from.
    eigenvalues_pool : list
        List of eigenvalues to choose from.
    seed : int
        Seed for the random number generator.
    """

    rng = np.random.default_rng(seed)

    quantum_circuits = []

    for _ in range(num_circuits):

        observables = rng.choice(observables_pool, num_qubits, replace=True)
        eigenvalues = rng.choice(
            eigenvalues_pool, rng.integers(1, len(eigenvalues_pool) + 1), replace=False
        )

        quantum_circuit = [
            int(num_qubits),
            "".join(observables),
            eigenvalues.tolist(),
        ]

        for _ in range(num_blocks):
            num_one_qubit_gates = rng.integers(1, num_gates + 1)
            num_two_qubit_gates = num_gates - num_one_qubit_gates

            one_qubit_gates = rng.choice(one_qubit_gates_pool, num_one_qubit_gates)
            two_qubit_gates = rng.choice(two_qubit_gates_pool, num_two_qubit_gates)

            dic1 = {}
            for gate in one_qubit_gates:
                dic1[gate.tolist()] = [rng.integers(0, num_qubits).tolist()]

            dic2 = {}
            for gate in two_qubit_gates:
                dic2[gate.tolist()] = [
                    rng.choice(num_qubits, 2, replace=False).tolist()
                ]

            quantum_circuit.append(dic1 | dic2)
        quantum_circuits.append(quantum_circuit)

    return QuantumCircuit(quantum_circuits)


def save_quantum_circuit(QuantumCircuit, filename="quantum_circuit"):
    """Save a quantum circuit to a JSON file."""

    with open(filename + ".json", "w", encoding="utf-8") as file:
        json.dump(QuantumCircuit, file, ensure_ascii=False, indent=4)


def load_quantum_circuit(filename="quantum_circuit"):
    """Load a quantum circuit from a JSON file."""

    with open(filename + ".json", "r", encoding="utf-8") as file:
        q = json.load(file)

    return QuantumCircuit(q)
